"de_real"
{
   "name" "Example"
   "t_arms" "models/weapons/t_arms_anarchist.mdl"
   "ct_arms" "models/weapons/ct_arms_gign.mdl"
   "t_models"
   {
      "tm_anarchist" ""
      "tm_anarchist_variantA" ""
      "tm_anarchist_variantB" ""
      "tm_anarchist_variantC" ""
      "tm_anarchist_variantD" ""
   }
   "ct_models"
	{
		"ctm_gsg9"""
		"ctm_gsg9_variantA"""
		"ctm_gsg9_variantB"""
		"ctm_gsg9_variantC"""
		"ctm_gsg9_variantD"""
	}
}